# Generated by Django 4.1 on 2023-03-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banky_app', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='rActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
