# Generated by Django 4.1 on 2023-03-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banky_app', '0005_ractivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ractivities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
