# Generated by Django 4.1 on 2023-03-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banky_app', '0006_ractivities_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ractivities',
            options={'verbose_name_plural': 'rActivities'},
        ),
        migrations.AlterField(
            model_name='ractivities',
            name='date_created',
            field=models.DateField(),
        ),
    ]
